# Generated by Django 5.2.14 on 2026-05-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, verbose_name='ID пользователя MAX')),
                ('phone', models.CharField(max_length=16, verbose_name='Телефон')),
                ('child_full_name', models.CharField(max_length=255, verbose_name='ФИО ребёнка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('status', models.CharField(choices=[('submitted', 'Отправлена')], default='submitted', max_length=16, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting_text', models.TextField(default='👋 Добро пожаловать!\n\nЯ помогу вам оставить заявку. Давайте начнём.\n\n📞 Пожалуйста, введите ваш номер телефона в формате +7XXXXXXXXXX:', verbose_name='Приветственное сообщение')),
                ('phone_prompt', models.TextField(default='📞 Введите номер телефона в формате +7XXXXXXXXXX:', verbose_name='Запрос номера телефона')),
                ('phone_error', models.TextField(default='❌ Неверный формат номера телефона.\n\nВведите номер в формате +7XXXXXXXXXX (знак + и 11 цифр):', verbose_name='Ошибка валидации телефона')),
                ('name_prompt', models.TextField(default='👤 Введите ФИО ребёнка полностью (Фамилия Имя Отчество):', verbose_name='Запрос ФИО ребёнка')),
                ('confirmation_template', models.TextField(default='📋 Проверьте введённые данные:\n\n📞 Телефон: {phone}\n👤 ФИО ребёнка: {name}\n\nВсё верно?', verbose_name='Шаблон подтверждения (используйте {phone} и {name})')),
                ('completion_text', models.TextField(default='✅ Ваша заявка успешно отправлена!\n\nМы свяжемся с вами в ближайшее время. Спасибо!', verbose_name='Сообщение после отправки заявки')),
                ('edit_phone_prompt', models.TextField(default='✏️ Введите новый номер телефона в формате +7XXXXXXXXXX:', verbose_name='Запрос нового номера телефона (редактирование)')),
                ('edit_name_prompt', models.TextField(default='✏️ Введите новое ФИО ребёнка:', verbose_name='Запрос нового ФИО (редактирование)')),
            ],
            options={
                'verbose_name': 'Настройки бота',
                'verbose_name_plural': 'Настройки бота',
            },
        ),
        migrations.CreateModel(
            name='BotSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='ID пользователя MAX')),
                ('current_step', models.CharField(choices=[('waiting_phone', 'Ожидание телефона'), ('waiting_name', 'Ожидание имени'), ('confirming', 'Подтверждение'), ('editing_phone', 'Редактирование телефона'), ('editing_name', 'Редактирование имени'), ('done', 'Завершено')], default='waiting_phone', max_length=32, verbose_name='Текущий шаг')),
                ('phone', models.CharField(blank=True, default='', max_length=16, verbose_name='Телефон')),
                ('child_name', models.CharField(blank=True, default='', max_length=255, verbose_name='ФИО ребёнка')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Сессия бота',
                'verbose_name_plural': 'Сессии бота',
            },
        ),
    ]
